Renable other jobs, try to be clever with declaration

diff --git a/.azure-pipelines/azure-pipelines.yml b/.azure-pipelines/azure-pipelines.yml
--- a/.azure-pipelines/azure-pipelines.yml
+++ b/.azure-pipelines/azure-pipelines.yml
@@ -1,6 +1,8 @@
 variables:
   CACHE_VERSION: 20201102
   isPullRequest: $[startsWith(variables['Build.SourceBranch'], 'refs/pull/')]
+  PYTHON_MINIMUM_VERSION: "3.9"
+  PYTHON_TESTING_VERSION: "3.11"
 
 stages:
 - stage: prepare
@@ -14,11 +16,11 @@ stages:
     steps:
       - checkout: none
 
-      # Use Python >=3.9 for syntax validation
+      # Use Earliest Python for syntax validation
       - task: UsePythonVersion@0
         displayName: Set up python
         inputs:
-          versionSpec: 3.9
+          versionSpec: ${{ variables.PYTHON_MINIMUM_VERSION }}
 
       # Run syntax validation on a shallow clone
       - bash: |
@@ -63,27 +65,41 @@ stages:
     displayName: PR
   condition: and(eq(dependencies.prepare.outputs['setup.constants.NEWSFRAGMENT_WAITING'], 'false'),
                  succeeded())
-  # dependsOn:
-  # - prepare
+  dependsOn:
+  - prepare
   variables:
     CURRENT_WEEK: $[ stageDependencies.prepare.setup.outputs['constants.CURRENT_WEEK'] ]
     TODAY_ISO: $[ stageDependencies.prepare.setup.outputs['constants.TODAY_ISO'] ]
 
   jobs:
+  - job: linux-bootstrap
+    pool:
+      vmImage: ubuntu-20.04
+    strategy:
+      matrix:
+        python${{ replace(variables.PYTHON_MINIMUM_VERSION, ".", "") }}:
+          PYTHON_VERSION: ${{ variables.PYTHON_MINIMUM_VERSION }}
+    timeoutInMinutes: 150
+    steps:
+    # Dependencies required for building gltbx
+    - script: |
+        sudo apt-get update
+        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
+      displayName: Install dependencies
+
+    - template: unix-build.yml
+      parameters:
+        conda_environment: .conda-envs/linux.txt
+
   - job: linux
     pool:
       vmImage: ubuntu-20.04
     strategy:
       matrix:
-        python311:
-          PYTHON_VERSION: 3.11
+        python${{ replace(variables.PYTHON_TESTING_VERSION, ".", "") }}:
+          PYTHON_VERSION: ${{ variables.PYTHON_TESTING_VERSION }}
     timeoutInMinutes: 150
     steps:
-    # Dependencies required for building gltbx
-    # - script: |
-    #     sudo apt-get update
-    #     sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
-    #   displayName: Install dependencies
 
     - template: unix-build-cmake.yml
       parameters:
@@ -94,71 +110,69 @@ stages:
       vmImage: macOS-latest
     strategy:
       matrix:
-        python311:
-          PYTHON_VERSION: 3.11
-    timeoutInMinutes: 250
+        python${{ replace(variables.PYTHON_TESTING_VERSION, ".", "") }}:
+          PYTHON_VERSION: ${{ variables.PYTHON_TESTING_VERSION }}
+    timeoutInMinutes: 150
     steps:
     - template: unix-build-cmake.yml
       parameters:
         conda_environment: .conda-envs/macos.txt
 
-  # - job: windows
-  #   pool:
-  #     vmImage: windows-latest
-  #   strategy:
-  #     matrix:
-  #       python39:
-  #         PYTHON_VERSION: 3.9
-  #   timeoutInMinutes: 150
-  #   steps:
-  #   - template: windows-build.yml
-  #     parameters:
-  #       conda_environment: .conda-envs/windows.txt
+  - job: windows
+    pool:
+      vmImage: windows-latest
+    strategy:
+      matrix:
+        python39:
+          PYTHON_VERSION: ${{ variables.PYTHON_TESTING_VERSION }}
+    timeoutInMinutes: 150
+    steps:
+    - template: windows-build.yml
+      parameters:
+        conda_environment: .conda-envs/windows.txt
 
-  # - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
-  #   - job: pr
-  #     displayName: ready to merge
-  #     dependsOn:
-  #     - linux
-  #     - macos
-  #     - windows
-  #     condition: and(eq(variables.isPullRequest, true), succeeded())
-  #     pool:
-  #       vmImage: ubuntu-20.04
-  #     steps:
-  #     - checkout: none
+  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
+    - job: pr
+      displayName: ready to merge
+      dependsOn:
+      - linux
+      - macos
+      - windows
+      condition: and(eq(variables.isPullRequest, true), succeeded())
+      pool:
+        vmImage: ubuntu-20.04
+      steps:
+      - checkout: none
 
-  #   - job: xfel
-  #     displayName: XFEL regression tests
-  #     dependsOn:
-  #     - linux
-  #     - macos
-  #     - windows
-  #     condition: and(eq(variables.isPullRequest, true), succeededOrFailed())
-  #     pool:
-  #       vmImage: ubuntu-20.04
-  #     steps:
-  #     - checkout: none
-  #     - task: DownloadPipelineArtifact@2
-  #       inputs:
-  #         allowFailedBuilds: true
-  #         patterns: "*/xfel-regression.*"
-  #         path: $(Pipeline.Workspace)/artifacts
-  #       continueOnError: True
-  #     - bash: |
-  #         set -eu
-  #         if [ ! -e artifacts ] || [ ! "$(\ls -A artifacts)" ]; then
-  #           echo "##[error]XFEL regression tests did not run"
-  #         else
-  #           cd artifacts
-  #           for D in *; do
-  #             echo "##[group]${D}"
-  #             cat "${D}/xfel-regression.txt"
-  #             echo "##[endgroup]"
-  #             cat "${D}/xfel-regression.output"
-  #             echo
-  #           done
-  #         fi
-  #       displayName: Report
-  #       condition: always()
-  #       workingDirectory: $(Pipeline.Workspace)/artifacts
+    - job: xfel
+      displayName: XFEL regression tests
+      dependsOn:
+      - linux
+      condition: and(eq(variables.isPullRequest, true), succeededOrFailed())
+      pool:
+        vmImage: ubuntu-20.04
+      steps:
+      - checkout: none
+      - task: DownloadPipelineArtifact@2
+        inputs:
+          allowFailedBuilds: true
+          patterns: "*/xfel-regression.*"
+          path: $(Pipeline.Workspace)/artifacts
+        continueOnError: True
+      - bash: |
+          set -eu
+          if [ ! -e artifacts ] || [ ! "$(\ls -A artifacts)" ]; then
+            echo "##[error]XFEL regression tests did not run"
+          else
+            cd artifacts
+            for D in *; do
+              echo "##[group]${D}"
+              cat "${D}/xfel-regression.txt"
+              echo "##[endgroup]"
+              cat "${D}/xfel-regression.output"
+              echo
+            done
+          fi
+        displayName: Report
+        condition: always()
+        workingDirectory: $(Pipeline.Workspace)/artifacts
