Disable others

diff --git a/.azure-pipelines/azure-pipelines.yml b/.azure-pipelines/azure-pipelines.yml
--- a/.azure-pipelines/azure-pipelines.yml
+++ b/.azure-pipelines/azure-pipelines.yml
@@ -115,50 +115,50 @@ stages:
   #     parameters:
   #       conda_environment: .conda-envs/windows.txt
 
-  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
-    - job: pr
-      displayName: ready to merge
-      dependsOn:
-      - linux
-      - macos
-      - windows
-      condition: and(eq(variables.isPullRequest, true), succeeded())
-      pool:
-        vmImage: ubuntu-20.04
-      steps:
-      - checkout: none
+  # - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
+  #   - job: pr
+  #     displayName: ready to merge
+  #     dependsOn:
+  #     - linux
+  #     - macos
+  #     - windows
+  #     condition: and(eq(variables.isPullRequest, true), succeeded())
+  #     pool:
+  #       vmImage: ubuntu-20.04
+  #     steps:
+  #     - checkout: none
 
-    - job: xfel
-      displayName: XFEL regression tests
-      dependsOn:
-      - linux
-      - macos
-      - windows
-      condition: and(eq(variables.isPullRequest, true), succeededOrFailed())
-      pool:
-        vmImage: ubuntu-20.04
-      steps:
-      - checkout: none
-      - task: DownloadPipelineArtifact@2
-        inputs:
-          allowFailedBuilds: true
-          patterns: "*/xfel-regression.*"
-          path: $(Pipeline.Workspace)/artifacts
-        continueOnError: True
-      - bash: |
-          set -eu
-          if [ ! -e artifacts ] || [ ! "$(\ls -A artifacts)" ]; then
-            echo "##[error]XFEL regression tests did not run"
-          else
-            cd artifacts
-            for D in *; do
-              echo "##[group]${D}"
-              cat "${D}/xfel-regression.txt"
-              echo "##[endgroup]"
-              cat "${D}/xfel-regression.output"
-              echo
-            done
-          fi
-        displayName: Report
-        condition: always()
-        workingDirectory: $(Pipeline.Workspace)/artifacts
+  #   - job: xfel
+  #     displayName: XFEL regression tests
+  #     dependsOn:
+  #     - linux
+  #     - macos
+  #     - windows
+  #     condition: and(eq(variables.isPullRequest, true), succeededOrFailed())
+  #     pool:
+  #       vmImage: ubuntu-20.04
+  #     steps:
+  #     - checkout: none
+  #     - task: DownloadPipelineArtifact@2
+  #       inputs:
+  #         allowFailedBuilds: true
+  #         patterns: "*/xfel-regression.*"
+  #         path: $(Pipeline.Workspace)/artifacts
+  #       continueOnError: True
+  #     - bash: |
+  #         set -eu
+  #         if [ ! -e artifacts ] || [ ! "$(\ls -A artifacts)" ]; then
+  #           echo "##[error]XFEL regression tests did not run"
+  #         else
+  #           cd artifacts
+  #           for D in *; do
+  #             echo "##[group]${D}"
+  #             cat "${D}/xfel-regression.txt"
+  #             echo "##[endgroup]"
+  #             cat "${D}/xfel-regression.output"
+  #             echo
+  #           done
+  #         fi
+  #       displayName: Report
+  #       condition: always()
+  #       workingDirectory: $(Pipeline.Workspace)/artifacts
