First attempt at adding xfel-regression

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -23,6 +23,9 @@ jobs:
             buildsys: libtbx
           - os: windows
             buildsys: libtbx
+    defaults:
+      run:
+        shell: bash
     runs-on: ${{ matrix.os }}-latest
     steps:
       - name: Checkout Repository
@@ -33,7 +36,6 @@ jobs:
         with:
           python-version: ${{ env.PYTHON_MINIMUM_VERSION }}
       - name: Prepare for Base Environment
-        shell: bash
         run: |
           OS="$(python -c "print('${{ runner.os }}'.lower())")"
           echo "ninja
@@ -52,7 +54,6 @@ jobs:
           echo "$(pwd)/conda_base/Library/bin" >> $GITHUB_PATH
           echo "$(pwd)/conda_base/" >> $GITHUB_PATH
       - name: Install Base Environment
-        shell: bash
         run: |
           python modules/dials/installer/bootstrap.py update base \
             --python "${{ matrix.buildsys == 'CMake' && env.PYTHON_TESTING_VERSION || env.PYTHON_MINIMUM_VERSION }}" \
@@ -60,10 +61,25 @@ jobs:
       - if: runner.os != 'Windows'
         run: echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV
       - name: Build
-        shell: bash
         run: python modules/dials/installer/bootstrap.py build ${BOOTSTRAP_FLAGS} ${BOOTSTRAP_BUILD_FLAGS}
+      - name: Create Installer
+        if: runner.buildsys == 'libtbx'
+        run: |
+          mamba install -yp ./conda_base conda-pack
+          pip3 uninstall dxtbx xia2
+          build/bin/libtbx.python modules/cctbx_project/libtbx/auto_build/create_installer.py \
+            --install_script  modules/dials/installer/dials_installer.py \
+            --version         dev$(date +"%Y%m%d") \
+            --license         modules/dials/LICENSE \
+            --readme          modules/dials/LICENSE \
+            --binary          tmp/dials-installer-dev
+      - uses: actions/upload-artifact@v4
+        if: runner.buildsys == 'libtbx'
+        with:
+          path: dist/dials-installer-dev.tar.gz
+          if-no-files-found: error
+          compression-level: 0
       - name: Prepare for cache restoration
-        shell: bash
         run: |
           set -x
           find . -name "dials.data*"
@@ -89,3 +105,51 @@ jobs:
           custom-arguments: modules/dials --regression
           click-to-expand: true
           custom-pytest: ${{ matrix.buildsys == 'CMake' && 'pytest' || 'build/bin/libtbx.python -mpytest' }}
+
+      - uses: insurgent-lab/is-in-pr-action@129df59687402c4a9c81a9a9e88d7448cdbba541 # v0.2.0
+
+  is-in-pr:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: insurgent-lab/is-in-pr-action@v0.2.0
+        id: isInPR
+    outputs:
+      result: ${{ steps.isInPR.outputs.result }}
+
+  test_xfel:
+    name: Test XFEL
+    runs-on: ubuntu-latest
+    needs: [os-in-pr, build_test]
+    if: ${{ needs.is-in-pr.outputs.result == 'true' }}
+    steps:
+      - uses: actions/download-artifact@v4
+      - name: Install DIALS
+        run: |
+          tar -xf dials-installer-dev.tar.gz
+          cd dials-installer
+          ./install --prefix=../dist --raw-prefix
+          cd ..
+          rm -rf ./dials-installer*
+          echo "$(pwd)/dist/conda_base/bin" >> $GITHUB_PATH
+          echo "$(pwd)/dist/build/bin" >> $GITHUB_PATH
+      - name: Install XFEL-regression
+        working-directory: ./dist
+        run: |
+          mamba install -yp ./conda_base bash distro git-lfs mpi4py openmpi pandas
+          git clone https://gitlab.com/cctbx/xfel_regression.git modules/xfel_regression
+          cd modules/xfel_regression
+          git lfs install --local
+          git lfs pull
+          libtbx.configure xfel_regression
+          wait
+      - name: Run xfel_regression tests
+        run: |
+          mkdir tests
+          libtbx.run_tests_parallel module=xfel_regression nproc=auto && {
+            echo "XFEL regression tests passed on Python $(PYTHON_VERSION) $(Agent.OS)" > ../xfel-regression.output
+          } || {
+            echo "::error XFEL-regression tests failed"
+            echo "(test exit)"
+            exit 1
+          }
